### ISSUE TITLE
redis-geo?

### ISSUE THREAD

**Issue by sirvon** [arjunmehta/node-geo-proximity#18]
Does this lib require or take advantage of redis-geo/dynamic redis?

**Comment by arjunmehta** [comment]
It definitely does not require it but I do intend to add it as an option in the `initialize` method.

It will expose the following Redis commands:

- GEOADD
- GEODIST
- GEOHASH
- GEOPOS
- GEORADIUS
- GEORADIUSBYMEMBER

Especially since these commands will be baked into Redis from 3.2 on, I'll get on this soon.

The methods/algorithms supplied in this module will likely become fallbacks eventually and native methods will take over as they'll likely be much faster! I plan on doing some performance comparisons as well.

The methods in this module however will still be really useful if distributed computation is desired.

**Comment by arjunmehta** [comment]
Thinking this through and it kind of doesn't make sense to use these redis commands in this module. People who have access to those redis-geo commands should just be able to use the node-redis module to access the redis commands directly.

This module can be used as a fallback. A very slow (comparatively) fallback. :)

**Comment by arjunmehta** [comment]
Implementing in [v3.0.0](https://github.com/arjunmehta/node-georedis)
Renaming module to `georedis` with many API changes.

Would you care to beta test? `npm install georedis` `:)`

Takes advantage of all [Redis-Geo commands](http://redis.io/commands#geo) if they are available.

**Comment by sirvon** [comment]
thanks for this!

**Comment by arjunmehta** [comment]
]()
