### ISSUE TITLE
`nearby()` results not sorted by distance from point?

### ISSUE THREAD

**Issue by doapp-ryanp** [arjunmehta/node-geo-proximity#19]
I want to find the closest nearby point to my point, but the results from `nearby()` while its a list (implies order) is not ordered. Said another way the 1st entry in the list is not the closest to the point I asked for nearby points to.

How do I find the closest of the nearby locations to my point?

**Comment by sirvon** [comment]
good damn question! I thought that was implied functionality given the nature of the library. and we await....

**Comment by arjunmehta** [comment]
@doapp-ryanp This unfortunately is not an easy thing to do without additional computational load.

I have some good news and bad news related to this modules.

Bad news first: it's unlikely I'd implement any kind of sorting algorithms on results because this is already something the [geolib](https://www.npmjs.com/package/geolib) module does. Use that module to manipulate results from this module if needed. Look at `orderByDistance` for this particular problem. I may make this module more compatible with `geolib` so that results can easily be passed into it without any manipulation. But that means changing the way objects get returned which is a breaking change and would mean major version bump (as per semver).

Good news: this module is likely to become obsolete very soon because Redis is wrapping in a native implementation of the algorithms used here and this will be WAYYYY faster, more accurate and will have sorting baked in as well as many other great features.

[http://redis.io/commands/georadius](Redis GEORADIUS command). Check out the related commands.

**Comment by arjunmehta** [comment]
Changed my mind on this. I think I will implement sorting, but it will be in a 3.x.x release and will be wrapped up with support for the new Redis Geo commands. `:D`
Please be patient, while I try and fit it all in.

**Comment by doapp-ryanp** [comment]
OK thanks.  I will try that out

In my use case I don't want redis (I have a small source set and don't want the extra dependency).  I am currently using fakeredis to pull this off.  Only reason I mention this, is I don't want your lib to go away :)

**Comment by arjunmehta** [comment]
@doapp-ryanp @sirvon I'm releasing [v3.0.0](https://github.com/arjunmehta/node-georedis) as a new module called `georedis`.

This uses the native geo commands in redis if they are available, and fallback to an emulation mode if they aren't. This means it should work using fakeredis. And I've added [sorting capabilities as well as a number of other options](https://github.com/arjunmehta/node-georedis#search-for-nearby-locations).

``` javascript
var options = {
  withCoordinates: true, // Will provide coordinates with locations, default false
  withHashes: true, // Will provide a 52bit Geohash Integer, default false
  withDistances: true, // Will provide distance from query, default false
  order: 'ASC', // or 'DESC' or true (same as 'ASC'), default false
  units: 'm', // or 'km', 'mi', 'ft', default 'm'
  count: 100, // Number of results to return, default undefined
  accurate: true // Useful if in emulated mode and accuracy is important, default false
}

// look for all points within ~5000m of Toronto with the options.
geo.nearby({latitude: 43.646838, longitude: -79.403723}, 5000, options, function(err, locations){
  if(err) console.error(err)
  else console.log('nearby locations:', locations)
})
```

Sorting by distance is VERY slow in emulation mode, especially for large returned results. If you care about performance, consider looking into the soon to be available native geo commands in redis, which this module takes advantage of. Pretty sweet! :)

The API has changed, but if you can, beta testing would be appreciated.
`npm install georedis`

**Comment by doapp-ryanp** [comment]
Thanks - I will try it out in the next few weeks, I wont be able to use real redis because AWS elasticache wont have new version for quite some time and the code I'm working on is in lambda which currently does not have access to elasticache.

**Comment by arjunmehta** [comment]
Cool! :) Let me know
